### ISSUE TITLE
Add tablet support

### ISSUE THREAD

**Issue by hamen** [alter-ego/unisannio-reboot#54]

**Comment by ShAdOwNeT88** [comment]
Perfetto mi è stata assegnata la card :smile:

**Comment by ShAdOwNeT88** [comment]
http://of-electric-sheep.blogspot.dk/2012/04/how-to-scale-your-android-layouts-to.html

Potrebbe fare al nostro caso questo tool se funzionasse? Domani è na cosa che devo provare.

**Comment by ShAdOwNeT88** [comment]
![screenshot_2015-09-12-12-39-19](https://cloud.githubusercontent.com/assets/1220893/9831150/97050500-594b-11e5-8ef4-6757e429ac52.png)
![screenshot_2015-09-12-12-38-44](https://cloud.githubusercontent.com/assets/1220893/9831149/96fe912a-594b-11e5-95c0-6658040e5562.png)
![screenshot_2015-09-12-12-38-37](https://cloud.githubusercontent.com/assets/1220893/9831151/970b9b36-594b-11e5-90bd-749c10f8959b.png)

Ecco alcuni screenshoot che ritraggono la situazione senza nessun tipo di modifica apportata.

**Comment by ShAdOwNeT88** [comment]
Alla fine a me il padding sembra adattarsi già molto bene anche alla versione tablet......

**Comment by ShAdOwNeT88** [comment]
Ho aggiunto il resize e la compatibilità anche con schermi large e xlarge così non dovremo avere nessun tipo di problemi con schermi dei tablet da 7 a 10.1

**Comment by hamen** [comment]
La versione tablet scala abbastanza bene, ma che ne pensi di aggiungere un po' di margine?
Stavo pensando a qualcosa di piu` Materia Design, tipo queste:

http://mms.businesswire.com/media/20150506005282/en/466406/5/Android_Tablet_03_recent_chats.jpg
http://designshack.net/wp-content/uploads/material-settings.jpg
http://photos2.appleinsidercdn.com/gallery/9699-1564-Screen-Shot-2014-06-25-at-11453-PM-xl.png

Potremmo addirittura pensare di usare un grosso background, con una foto di Benevento, come nel terzo screenshot. Flickr e` pieno di foto di Benevento con licenza CC che possiamo liberamente usare.
Prova a fare qualche tentativo e parliamone.

**Comment by ShAdOwNeT88** [comment]
Utilizzando la prima view quella di businesswire e inserendo come sfondo l'immagine di benevento penso che l'effetto sia carino....ma questo però lo possiamo fare solo per la versione tablet. Per la versione smartphone dubito che l'effetto sia apprezzabile perché verrebbe tutto più rimpicciolito e sarebbe difficoltoso poi per la consultazione delle notizie.

**Comment by ShAdOwNeT88** [comment]
Io penso che per il terzo link siano state progettate tre interfacce completamente differenti...a seconda dell'uso smartphone tablet 7 pollici tablet 10 pollici.

**Comment by hamen** [comment]
L'idea e` proprio realizzare due UI diverse per i due diversi tipi di device: http://developer.android.com/guide/practices/screens_support.html
La lista delle news avra` un valore _margin_ destro/sinistro che sullo smartphone sara` 0 e sul tablet, diciamo, 20dp, per esempio.

**Comment by ShAdOwNeT88** [comment]
Quindi l'idea è proprio di progettare un interfaccia ad hoc per il tablet mantenendo quella che abbiamo per la versione smartphone

**Comment by ShAdOwNeT88** [comment]
Quindi manterremo il menu uguale per tutti e due i layout quello che andiamo ad adattare usando l'immagine di sfondo anche è le news per quanto riguarda le varie informazioni di ateneo e segreteria.

**Comment by ShAdOwNeT88** [comment]
Dalle prime prove effettuate dando <android:background=@drawable/arco02> all'interno della activity main o in uno dei fragment questo è ciò che ottengo:

09-20 23:42:25.296  13073-13073/solutions.alterego.android.unisannio E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo{solutions.alterego.android.unisannio/solutions.alterego.android.unisannio.MainActivity}: android.view.InflateException: Binary XML file line #23: Error inflating class <unknown>
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2245)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2295)
            at android.app.ActivityThread.access$700(ActivityThread.java:150)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:175)
            at android.app.ActivityThread.main(ActivityThread.java:5279)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #23: Error inflating class <unknown>
            at android.view.LayoutInflater.createView(LayoutInflater.java:619)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:666)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:691)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:228)
            at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
            at solutions.alterego.android.unisannio.MainActivity.onCreate(MainActivity.java:39)
            at android.app.Activity.performCreate(Activity.java:5283)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2295)
            at android.app.ActivityThread.access$700(ActivityThread.java:150)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:175)
            at android.app.ActivityThread.main(ActivityThread.java:5279)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at android.view.LayoutInflater.createView(LayoutInflater.java:593)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:666)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:691)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:228)
            at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
            at solutions.alterego.android.unisannio.MainActivity.onCreate(MainActivity.java:39)
            at android.app.Activity.performCreate(Activity.java:5283)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2295)
            at android.app.ActivityThread.access$700(ActivityThread.java:150)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:175)
            at android.app.ActivityThread.main(ActivityThread.java:5279)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.OutOfMemoryError
            at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:596)
            at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:444)
            at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:817)
            at android.content.res.Resources.loadDrawable(Resources.java:2854)
            at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
            at android.view.View.<init>(View.java:3513)
            at android.view.ViewGroup.<init>(ViewGroup.java:446)
            at android.widget.FrameLayout.<init>(FrameLayout.java:101)
            at android.widget.FrameLayout.<init>(FrameLayout.java:97)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
            at android.view.LayoutInflater.createView(LayoutInflater.java:593)
            at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:56)
            at android.view.LayoutInflater.onCreateView(LayoutInflater.java:666)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:691)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:752)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:760)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:353)
            at android.support.v7.app.ActionBarActivityDelegateBase.setContentView(ActionBarActivityDelegateBase.java:228)
            at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:102)
            at solutions.alterego.android.unisannio.MainActivity.onCreate(MainActivity.java:39)
            at android.app.Activity.performCreate(Activity.java:5283)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2295)
            at android.app.ActivityThread.access$700(ActivityThread.java:150)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:175)
            at android.app.ActivityThread.main(ActivityThread.java:5279)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)

ad occhio e croce qualcosa non gli va più giù nel layout della activity main quando vai a dare un immagine di background a uno degli altri fragment o alla activity main stessa

**Comment by ShAdOwNeT88** [comment]
Potrebbe anche essere un problema di rendering dell'immagine essendo una xxhdpi forse non riesce a scalarla ad xhdpi oppure la risoluzione della foto che è 3497x5245

**Comment by mrsasha** [comment]
foto di 20MP? hmmmm, direi indicativamente sia questo: "Caused by: java.lang.OutOfMemoryError".

**Comment by ShAdOwNeT88** [comment]
Allora provo come prima cosa a ridimensionare la foto e a riprovare. Ti ringrazio per la dritta.

**Comment by ShAdOwNeT88** [comment]
Ecco una prima versione dell'app con layout tablet portrait, purtroppo allego le immagini dell'emulator dato che il dispositivo non cel'ho ancora sottomano appena possibile faccio degli screenshot direttamente da terminale.

<img width="1680" alt="schermata 2015-09-21 alle 21 31 46" src="https://cloud.githubusercontent.com/assets/1220893/10002611/7ba9973a-60a8-11e5-83f7-ef4f37023ca3.png">
![Uploading Schermata 2015-09-21 alle 21.31.52.png…]()
![Uploading Schermata 2015-09-21 alle 21.32.06.png…]()
![Uploading Schermata 2015-09-21 alle 21.32.10.png…]()

**Comment by ShAdOwNeT88** [comment]
Rimuovendo l'header e diminuendo lo spazio tra le news questo è l'effetto che otteniamo invece.
<img width="1680" alt="schermata 2015-09-21 alle 23 04 52" src="https://cloud.githubusercontent.com/assets/1220893/10005057/6d93bd58-60b5-11e5-9942-7442c34b65a2.png">
<img width="1680" alt="schermata 2015-09-21 alle 23 04 58" src="https://cloud.githubusercontent.com/assets/1220893/10005085/98091786-60b5-11e5-8dec-02a8062b5dd1.png">

**Comment by ShAdOwNeT88** [comment]
Ecco le ulteriori modifiche, centrate le news e le details di ingegneria diminuito lo spazio tra le news questo è il risultato che otteniamo: 
![device-2015-09-22-222615](https://cloud.githubusercontent.com/assets/1220893/10030832/f82180d0-6179-11e5-8182-422a2120b805.png)
![device-2015-09-22-223026](https://cloud.githubusercontent.com/assets/1220893/10030841/0a4157b8-617a-11e5-88ad-ea2790fcce71.png)
![device-2015-09-22-222712](https://cloud.githubusercontent.com/assets/1220893/10030855/292f6d40-617a-11e5-8def-7289e2c6d0fa.png)
